# Testing workflow for CI developments, reacts to push of branch 'devel-ci'
name: Testing CI build
run-name: Testing CI
on:
  push:
    branches:
      - devel-ci
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: uname -a
      - run: sudo modprobe btrfs
      - run: cat /proc/filesystems
      - run: gcc --version
      - run: df -HT
      - run: sudo apt-get install -y pkg-config gcc liblzo2-dev libzstd-dev libblkid-dev uuid-dev zlib1g-dev libext2fs-dev e2fsprogs libudev-dev python3-sphinx libaio-dev liburing-dev
      - name: Configure
        run: ./autogen.sh && ./configure
      - name: Make
        run: echo make V=1
      - name: Musl build
        run: echo sudo docker run kdave/ci-musl-x86_64 ./test-build $GITHUB_REF_NAME --disable-documentation --disable-backtrace --disable-libudev
      - name: Tests cli
        run: echo sudo make TEST_LOG=dump test-cli
      - run: echo "::error::Test failed"
      - run: echo "It works :rocket:" >> $GITHUB_STEP_SUMMARY
      - run: tests/annotate.sh >> $GITHUB_STEP_SUMMARY
  build-asan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo modprobe btrfs
      - run: sudo apt-get install -y pkg-config gcc liblzo2-dev libzstd-dev libblkid-dev uuid-dev zlib1g-dev libext2fs-dev e2fsprogs libudev-dev libaio-dev liburing-dev attr jq
      - name: Configure
        run: ./autogen.sh && ./configure --disable-documentation
      - name: Make (D=asan)
        run: make V=1 D=asan
      - name: Tests mkfs (asan)
        run: sudo make TEST_LOG=dump D=asan test-mkfs
      - name: Scan results
        run: cd tests && ./scan-results.txt
